### PR TITLE
Added root openapi.yaml file to reference the managedAttribute and

### PR DESCRIPTION
**Pull request by xuemeigan**
metadata yaml as well as generated html documentation files :
https://github.com/DINA-Web/object-store-specs/issues/51

For now we can only have one linked external doc due to below open PR:
https://github.com/OAI/OpenAPI-Specification/issues/1034

### CODE REVIEW

**Comment by cgendreau** [comment]
The PR should not include html files.

**Comment by xuemeigan** [comment]
Currently the path can link to the actual spec file, to see the individual spec in document format, I think we need the external doc link, which will point to the html file.

**Comment by cgendreau** [comment]
Paths should be included using the proper `$ref`:
```
paths:
  /v1/metadata: 
    $ref: 'metadata.yaml#/paths/~1v1~1metadata'
  /v1/managed-attribute:
    $ref: 'managedAttribute.yaml#/paths/~1v1~1managed-attribute'  
```
But we need 1 path element per $ref. It would also be ok to simply have 1 document named object-store-api.yaml

**Comment by cgendreau** [comment]
The id of the acMetadataCreator should not point to an agent, it's the identifier only.

**Pull request merged**
